# Generated by Django 5.0 on 2023-12-30 17:12

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("Item", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="item",
            name="price",
            field=models.FloatField(
                validators=[
                    django.core.validators.MinValueValidator(
                        0, "Price cannot be negative"
                    )
                ]
            ),
        ),
    ]
