version: "3"
services:
  django:
    build:
      context: .
      dockerfile: docker/django/Dockerfile
    restart: unless-stopped
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      DATABASE_HOST: ${DATABASE_HOST}
      DATABASE_PORT: ${DATABASE_PORT}
      SECRET_KEY: ${SECRET_KEY}
      STRIPE_API_KEY: ${STRIPE_API_KEY}
      STRIPE_PUBLIC_KEY: ${STRIPE_PUBLIC_KEY}
      STRIPE_BACK_URL: ${DOMAIN}
      CELERY_BROKER_URL: ${CELERY_BROKER_URL}
    hostname: django
    depends_on:
      postgres:
        condition: service_healthy
    entrypoint: python3 manage.py runserver 0.0.0.0:80

  celery_worker:
    build:
      context: .
      dockerfile: docker/django/Dockerfile
    hostname: celery_worker
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      DATABASE_HOST: ${DATABASE_HOST}
      DATABASE_PORT: ${DATABASE_PORT}
      SECRET_KEY: ${SECRET_KEY}
      STRIPE_API_KEY: ${STRIPE_API_KEY}
      STRIPE_PUBLIC_KEY: ${STRIPE_PUBLIC_KEY}
      STRIPE_BACK_URL: ${DOMAIN}
      CELERY_BROKER_URL: ${CELERY_BROKER_URL}
    entrypoint: celery -A celery_app.app worker --loglevel=info
    depends_on:
      postgres:
        condition: service_healthy
      redis:
        condition: service_started
      django:
        condition: service_started

  celery_flower:
    build:
      context: .
      dockerfile: docker/django/Dockerfile
    hostname: celery_flower
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      DATABASE_HOST: ${DATABASE_HOST}
      DATABASE_PORT: ${DATABASE_PORT}
      SECRET_KEY: ${SECRET_KEY}
      STRIPE_API_KEY: ${STRIPE_API_KEY}
      STRIPE_PUBLIC_KEY: ${STRIPE_PUBLIC_KEY}
      STRIPE_BACK_URL: ${DOMAIN}
      CELERY_BROKER_URL: ${CELERY_BROKER_URL}
    entrypoint: celery
    command: -A celery_app.app flower
    depends_on:
      redis:
        condition: service_started
      django:
        condition: service_started

  celery_beat:
    build:
      context: .
      dockerfile: docker/django/Dockerfile
    hostname: celery_beat
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      DATABASE_HOST: ${DATABASE_HOST}
      DATABASE_PORT: ${DATABASE_PORT}
      SECRET_KEY: ${SECRET_KEY}
      STRIPE_API_KEY: ${STRIPE_API_KEY}
      STRIPE_PUBLIC_KEY: ${STRIPE_PUBLIC_KEY}
      STRIPE_BACK_URL: ${DOMAIN}
      CELERY_BROKER_URL: ${CELERY_BROKER_URL}
    entrypoint: celery
    command: -A celery_app.app beat
    depends_on:
      redis:
        condition: service_started
      django:
        condition: service_started

  postgres:
    image: "postgres:15"
    restart: unless-stopped
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    hostname: ${DATABASE_HOST}
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U ${POSTGRES_USER}" ]
      interval: 2s
      retries: 10
    volumes:
      - ${POSTGRES_DATA_VOLUME_DIR}:/var/lib/postgresql/data

  redis:
    image: "redis:alpine"
    hostname: "redis"

  nginx:
    build:
      context: .
      dockerfile: docker/nginx/Dockerfile
    restart: unless-stopped
    hostname: nginx
    ports:
      - "8080:80"
    depends_on:
      - "django"
      - "celery_worker"
      - "celery_flower"
      - "celery_beat"
    volumes:
      - ./static:/static