# Generated by Django 5.0 on 2023-12-31 08:37

import django.core.validators
import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("Item", "0002_alter_item_price"),
        ("sessions", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Payment",
            fields=[
                (
                    "uuid",
                    models.UUIDField(
                        default=uuid.uuid4,
                        primary_key=True,
                        serialize=False,
                        unique=True,
                    ),
                ),
                ("client_secret", models.CharField(max_length=120)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("waiting", "Waiting for payment"),
                            ("created", "Created"),
                            ("canceled", "Canceled"),
                            ("success", "Success"),
                        ],
                        max_length=60,
                    ),
                ),
                (
                    "session_key",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="sessions.session",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="PaymentItem",
            fields=[
                (
                    "uuid",
                    models.UUIDField(
                        default=uuid.uuid4,
                        primary_key=True,
                        serialize=False,
                        unique=True,
                    ),
                ),
                (
                    "count",
                    models.IntegerField(
                        validators=[
                            django.core.validators.MinValueValidator(
                                1, "Count cannot be negative or zero"
                            )
                        ]
                    ),
                ),
                (
                    "item",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="Item.item"
                    ),
                ),
                (
                    "payment",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="Payment.payment",
                    ),
                ),
            ],
        ),
    ]
